server:
  port: 8082

# Conexion base de datos
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;
    username: sa
    password: sa
  sql:
    init:
      data-locations: classpath:movie.sql #Archivo para inicializar la base de datos
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

# Actuator
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Movie Microservice