server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AlPetrovich/Microservices-CTD
          searchPaths: microservices-config

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka #contenedor de eureka

